### ISSUE TITLE
已放弃此项目的开发和维护

### ISSUE THREAD

**Issue by sutras** [sutras/sard#2]
如果只考虑兼容小程序，且一定要用react开发，taro或许是一个选择；
如果要适用到H5会有些许的兼容性问题，适用到APP的兼容问题就更大了；
另外，taro3重运行的实现方式，对性能影响太大；你需要显著减少页面首次渲染的节点，否则会白屏很久；另外，更新操作会对整个页面的节点进行遍历，页面节点多时会有明显的延迟，除非涉及到更新操作的组件都使用 CustomWrapper 组件包裹起来（sard组件库中的大量组件都使用到CustomWrapper），这会增加编程的复杂度和心智负担。

基于以上原因，已放弃此项目开发和维护，转投到 uniapp 的生态。

<p align="center">
    <img alt="logo" src="https://fastly.jsdelivr.net/npm/@sard/assets/logo.svg" width="120" height="120" style="margin-bottom: 10px;">
</p>

<h1 align="center">Sard Uniapp</h1>

<p align="center">sard-uniapp 是一套基于 Uniapp + Vue3 框架开发的兼容多端的 UI 组件库。</p>

<p align="center">
  📖 <a href="http://sutras.gitee.io/sard-uniapp-docs">文档网站</a>&nbsp;&nbsp;&nbsp;&nbsp;
  🧑🏻‍🏫 <a href="http://sutras.gitee.io/sard-uniapp-docs/mobile/">案例演示</a>
</p>

**Comment by XuJin186** [comment]
大哥  没必要啊  你这ui是看起来最舒服的

**Comment by github-cherry** [comment]
> 如果只考虑兼容小程序，且一定要用react开发，taro或许是一个选择； 如果要适用到H5会有些许的兼容性问题，适用到APP的兼容问题就更大了； 另外，taro3重运行的实现方式，对性能影响太大；你需要显著减少页面首次渲染的节点，否则会白屏很久；另外，更新操作会对整个页面的节点进行遍历，页面节点多时会有明显的延迟，除非涉及到更新操作的组件都使用 CustomWrapper 组件包裹起来（sard组件库中的大量组件都使用到CustomWrapper），这会增加编程的复杂度和心智负担。
> 
> 基于以上原因，已放弃此项目开发和维护，转投到 uniapp 的生态。
> 
> <img alt="logo" width="120" height="120" src="https://camo.githubusercontent.com/538c458d2339d75c3c31259ac2919fceddbad8fc00a41f90a727e5ad3d02094d/68747470733a2f2f666173746c792e6a7364656c6976722e6e65742f6e706d2f40736172642f6173736574732f6c6f676f2e737667">
> 
> # Sard Uniapp
> sard-uniapp 是一套基于 Uniapp + Vue3 框架开发的兼容多端的 UI 组件库。
> 
> 📖 [文档网站](http://sutras.gitee.io/sard-uniapp-docs)     🧑🏻‍🏫 [案例演示](http://sutras.gitee.io/sard-uniapp-docs/mobile/)

你的组件库真挺不错的，uniapp版的也不错。建议做做宣传，现在没几个知道你的sardUI

**Comment by haobarry** [comment]
原来如此

**Comment by chergn** [comment]
挺不错的移动端组件库

**Comment by chergn** [comment]
挺不错的移动端组件库，就是知道的人太少
